image: atlassian/default-image:latest

pipelines:
  default:
    - step:
        name: Build and Push Docker Images
        services:
          - docker
        script:
          # Login to Azure Container Registry
          - echo $AZURE_ACR_PASSWORD | docker login csdtms.azurecr.io --username csdtms --password-stdin
          
          # Build and push user_ms
          - docker build -t csdtms.azurecr.io/user_ms:latest ./backend/user_ms
          - docker push csdtms.azurecr.io/user_ms:latest
          
          # Build and push tournament_ms
          - docker build -t csdtms.azurecr.io/tournament_ms:latest ./backend/tournament_ms
          - docker push csdtms.azurecr.io/tournament_ms:latest

          # Build and push matchmaking
          - docker build -t csdtms.azurecr.io/matchmaking:latest ./backend/matchmaking
          - docker push csdtms.azurecr.io/matchmaking:latest

          # Build and push match_ms
          - docker build -t csdtms.azurecr.io/match_ms:latest ./backend/match_ms
          - docker push csdtms.azurecr.io/match_ms:latest

    - step:
        name: Deploy to Azure Container Instances
        script:
          # Login to Azure
          - az login --username kelyn.wong.2022@scis.smu.edu.sg --password $AZURE_PASSWORD
          
          # Deploy user_ms
          - az container create --resource-group tms --name user-ms --image csdtms.azurecr.io/user_ms:latest --cpu 1 --memory 1.5 --registry-login-server csdtms.azurecr.io --ip-address public

          # Deploy tournament_ms
          - az container create --resource-group tms --name tournament-ms --image csdtms.azurecr.io/tournament_ms:latest --cpu 1 --memory 1.5 --registry-login-server csdtms.azurecr.io --ip-address public

          # Deploy matchmaking
          - az container create --resource-group tms --name matchmaking --image csdtms.azurecr.io/matchmaking:latest --cpu 1 --memory 1.5 --registry-login-server csdtms.azurecr.io --ip-address public

          # Deploy match_ms
          - az container create --resource-group tms --name match-ms --image csdtms.azurecr.io/match_ms:latest --cpu 1 --memory 1.5 --registry-login-server csdtms.azurecr.io --ip-address public