GET http://localhost:8080/Tournaments


###
GET http://localhost:8080/Tournaments/2

###
DELETE http://localhost:8080/Tournaments/1


###
POST http://localhost:8080/Tournaments
Content-Type: application/json

{
    "title": "I, Human"
}

###
PUT http://localhost:8080/Tournaments/4
Content-Type: application/json

{
    "title": "Sapiens"
}

###
GET http://localhost:8080/Tournaments/2/reviews

###
POST http://localhost:8080/Tournaments/1/reviews
Content-Type: application/json

{
    "review": "Terrible Tournament!"
}

###
PUT http://localhost:8080/Tournaments/2/reviews/3
Content-Type: application/json

{
    "review": "Should be bad!"
}

###
DELETE http://localhost:8080/Tournaments/1/reviews/5