GET http://localhost:8080/api/users


###
GET http://localhost:8080/api/users/1


###
POST http://localhost:8080/api/users 
Content-Type: application/json
{
  "username": "nylekwong2",
  "fullname": "nylek wong",
  "password": "password",
  "gender": "Female",
  "email": "kelynwonget@gmail.com",
  "role": "Admin",
  "rank": null,
  "country": "Singapore"
}


###
PUT http://localhost:8080/api/users/1 
Content-Type: application/json
{
  "username": "nylekwong2",
  "fullname": "nylek wong lala",
  "password": "password123",
  "gender": "Male",
  "email": "kelynwonget@gmail.commmm",
  "role": "User",
  "rank": null,
  "country": "Malaysia"
}


###
DELETE http://localhost:8080/api/users/1